# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6018eff4642c173f428a62a9973ee101496fd4a02bab44338d6a547832d7eb6ebdb5c8d327b3e0f894afc8c7c91ac876bd811cd0bb6397a5ff02cc9dfee86c08

test:
  secret_key_base: bfd83d3d4b2683058e74dde1aa7a3771005505b21a06c75fd6f0894402bfd77f6b0cfc132e2911f1c696cb37e1e40c6c349aa7b09c9e1d7fc08a1a0c9143f7db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
